---
version: 2

models:
  - name: restricted_layer__dbt_data_privacy_restricted_layer__consents
    description: |
      This is the truth of single source of consent agreements.
    meta:
      data_privacy:
        - id: data_analysis_layer
          config:
            enabled: true
            materialized: view
            database: var('data_analysis_layer')
            schema: "dbt_data_privacy_data_analysis_layer"
            alias: "consents"
            grant_access_to:
              - project: var('restricted_layer_project')
                dataset: "dbt_data_privacy_restricted_layer"
            tags: []
            labels:
              modeled_by: dbt
          extra_meta:
            database_alias: data_analysis_layer

    columns:
      - name: user_id
        description: "User ID"
        meta:
          data_privacy:
            level: confidential
        tests:
          - not_null
          - relationships:
              to: ref("restricted_layer__dbt_data_privacy_seed__users")
              field: "user_id"
      - name: pseudonymized_user_id
        description: "Pseudonymized user ID"
        tests:
          - not_null
      - name: data_analysis_agree
        description: "Consent agree of data analysis"
        meta:
          data_privacy:
            level: internal
      - name: data_sharing_agree
        description: "Consent agree of data sharing"
        tests:
          - not_null
        meta:
          data_privacy:
            level: internal
