---
version: 2

models:
  - name: restricted_layer__dbt_data_privacy_restricted_layer__users
    description: |
      Users' table
    meta:
      data_privacy:
        - config:
            enabled: true
            database: var('data_analysis_layer')
            schema: "dbt_data_privacy_data_analysis_layer"
            alias: "consents"
          grant_access_to:
            - project: var('restricted_layer_project')
              dataset: "demo_source_data"
          tags: []
          labels:
            modeled_by: dbt
          extra:
            project_alias: data_analysis_project

    columns:
      - name: id
        description: "Raw number"
        meta:
          data_privacy:
            level: internal
        tests:
          - not_null
      - name: user_id
        description: "User ID"
        meta:
          data_privacy:
            level: confidential
        tests:
          - not_null
          - relationships:
              to: ref("restricted_layer__dbt_data_privacy_seed__users")
              field: "user_id"
      - name: name
        description: "User's name"
        meta:
          data_privacy:
            level: restricted
        tests:
          - not_null
      - name: email
        description: "User's email"
        meta:
          data_privacy:
            level: restricted
        tests:
          - not_null
