---
name: 'dbt_data_privacy_integration_tests'
version: '0.0.1'
config-version: 2

require-dbt-version: [">=1.1.0"]

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
asset-paths: ["assets"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:  # directories to be removed by `dbt clean`
  - "target"
  - "dbt_modules"

flags:
  send_anonymous_usage_stats: false
  use_colors: true
  warn_error_options:
    silence:
      - ProjectFlagsMovedDeprecation


models:
