---
version: 2

models:
  - name: restricted_layer__dbt_data_privacy_restricted_layer__items
    description: |
      Items' table
    meta:
      data_privacy:
        - config:
            enabled: true
            database: var('data_analysis_layer')
            schema: "dbt_data_privacy_data_analysis_layer"
            alias: "consents"
          grant_access_to:
            - project: var('restricted_layer_project')
              dataset: "demo_source_data"
          tags: []
          labels:
            modeled_by: dbt
          extra:
            project_alias: data_analysis_project

    columns:
      - name: id
        description: "Item ID"
        meta:
          data_privacy:
            level: public
        tests:
          - not_null
      - name: name
        description: "Item name"
        meta:
          data_privacy:
            level: public
        tests:
          - not_null
