---
version: 2

models:
  - name: restricted_layer__dbt_data_privacy_restricted_layer__items
    description: |
      Items' table

      ## NOTE
      - XXX
      - XXX
    config:
      meta:
        data_privacy:
          - name: data_analysis_layer__dbt_data_privacy_data_analysis_layer__items
            objective: data_analysis
            config:
              enabled: true
              materialized: view
              database: var('data_analysis_layer')
              schema: "dbt_data_privacy_data_analysis_layer"
              alias: "items"
              grant_access_to:
                - project: var('restricted_layer')
                  dataset: "dbt_data_privacy_restricted_layer"
              tags: []
              labels:
                modeled_by: dbt
            extra_meta:
              database_alias: data_analysis_layer

    columns:
      - name: id
        description: "Item ID"
        config:
          meta:
            data_privacy:
              level: public
        tests:
          - not_null
      - name: name
        description: "Item name"
        config:
          meta:
            data_privacy:
              level: public
        tests:
          - not_null
