{% macro generate_privacy_protected_model_sql(
    objective,
    materialized,
    database,
    schema,
    alias,
    reference,
    columns,
    adapter_config={},
    unknown_config={},
    where=none,
    relationships=none,
    tags=[],
    labels={},
    persist_docs={"relation": true, "columns": true},
    enabled=True,
    full_refresh=none
  ) %}
  {{- return(adapter.dispatch('generate_privacy_protected_model_sql', 'dbt_data_privacy')(
      objective=objective,
      materialized=materialized,
      database=database,
      schema=schema,
      alias=alias,
      tags=tags,
      labels=labels,
      persist_docs=persist_docs,
      adapter_config=adapter_config,
      unknown_config=unknown_config,
      reference=reference,
      columns=columns,
      where=where,
      relationships=relationships,
      enabled=enabled,
      full_refresh=full_refresh,
      **kwargs )) -}}
{% endmacro %}

{% macro bigquery__generate_privacy_protected_model_sql(
    objective,
    materialized,
    database,
    schema,
    alias,
    reference,
    columns,
    adapter_config={},
    unknown_config={},
    where=none,
    tags=[],
    labels={},
    persist_docs={"relation": true, "columns": true},
    relationships=none,
    enabled=True,
    full_refresh=none
  ) %}

  {% if columns | length == 0 %}
    {{ exceptions.raise_compiler_error("No columns for {}.{}.{}".format(database, schema, alias)) }}
  {% endif %}

  {%- set config = dbt_data_privacy.get_data_privacy_config_by_objective(objective) %}
  {%- set data_handling_standards = config.get('data_handling_standards') %}
  {%- set secured_columns = dbt_data_privacy.get_secured_columns(data_handling_standards, columns) %}

  {% set restructured_secured_columns = dbt_data_privacy.restructure_secured_columns(secured_columns) %}
  {% set restructured_secured_expressions = dbt_data_privacy.convert_secured_columns_to_expressions(restructured_secured_columns) %}

  {# Generate a model SQL #}
  {%- set model_sql -%}
-- This was automatically generated by the `dbt-data-privacy` package.
{{'{{'}}
  config(
    materialized={{- dbt_data_privacy.safe_quote(materialized) -}},
    database={{- dbt_data_privacy.safe_quote(database) -}},
    schema={{- dbt_data_privacy.safe_quote(schema) -}},
    alias={{- dbt_data_privacy.safe_quote(alias) -}},
    {% if "grant_access_to" in adapter_config -%}
    grant_access_to=[
      {%- for x in adapter_config["grant_access_to"] %}
      {
        {%- if "project" in x and "dataset" in x %}
        "project": {{ dbt_data_privacy.safe_quote(x.get("project")) }},
        "dataset": {{ dbt_data_privacy.safe_quote(x.get("dataset")) }},
        {%- elif "database" in x and "schema" in x %}
        "project": {{ dbt_data_privacy.safe_quote(x.get("database")) }},
        "dataset": {{ dbt_data_privacy.safe_quote(x.get("schema")) }},
        {%- else %}
          {% do exceptions.raise_compiler_error("unexpected grant_access_to: {}".format(x)) %}
        {%- endif %}
      },
      {%- endfor %}
    ],{%- endif %}
    tags={{ tags | unique | sort }},
    labels={
      {% for k, v in labels.items() -%}
      {{ '"' ~ k ~ '"' }}: {{ dbt_data_privacy.safe_quote(v) }},
      {%- endfor %}
    },
    {%- for k, v in unknown_config.items() %}
    {{ k }}={{ dbt_data_privacy.safe_quote(v) }},
    {%- endfor %}
    persist_docs={{ persist_docs }},
    full_refresh={{ full_refresh }},
    enabled={{ enabled }}
  )
{{'}}'}}

WITH privacy_protected_model AS (
  SELECT
    {%- for column_name, restructured_secured_expression in restructured_secured_expressions.items() %}
    {{ restructured_secured_expression }} AS `{{- column_name -}}`,
    {%- endfor %}
  FROM
    {%- if dbt_data_privacy.is_macro_expression(reference) %}
    {{ '{{ ' ~ reference ~ ' }}'}}
    {%- else %}
    {{ reference }}
    {%- endif %}
  {%- if where is not none %}
  WHERE
    {{ where }}
  {% endif -%}
)

SELECT
  source.*,
FROM privacy_protected_model AS source
{% if relationships is not none and dbt_data_privacy.validate_relationships(relationships)  -%}
JOIN {{ '{{ ' ~ relationships["to"] ~ ' }}' }} AS target
  ON {% for k, v in relationships["fields"].items() -%}
    {%- if not loop.first -%}AND {% endif -%}
    source.{{ k }} = target.{{ v }}
  {% endfor -%}
{% if "where" in relationships and relationships["where"] | length > 0 -%}
WHERE
  {{ relationships["where"] }}
{%- endif %}
{%- endif %}
  {% endset %}

  {{- return(model_sql) -}}
{% endmacro %}
