-- This was automatically generated by the `dbt-data-privacy` package.
-- noqa: disable=all
{{
  config(
    materialized="view",
    database=var('data_analysis_layer'),
    schema="dbt_data_privacy_data_analysis_layer_legacy",
    alias="items",
    grant_access_to=[
      {
        "project": var('restricted_layer'),
        "dataset": "dbt_data_privacy_restricted_layer_legacy",
      },
    ],
    tags=['data_analysis', 'dbt_data_privacy'],
    labels={
      "modeled_by": "dbt",
    },
    persist_docs={'relation': True, 'columns': True},
    full_refresh=None,
    enabled=True
  )
}}

WITH privacy_protected_model AS (
  SELECT
    id AS `id`,
    name AS `name`,
  FROM
    {{ ref('restricted_layer__dbt_data_privacy_restricted_layer_legacy__items') }} AS __original_table
)

SELECT
  __source.*,
FROM privacy_protected_model AS __source
