default:
  outputs:
    bigquery:
      type: bigquery
      method: oauth
      project: "ubie-oss-data-engineering"
      dataset: "dbt_data_privacy"
      priority: "{{ env_var('DBT_BIGQUERY_PRIORITY', 'interactive') }}"
      threads: |
        {{ env_var("DBT_THREADS", 10) | as_number }}
      location: "US"
      impersonate_service_account: "dbt-data-privacy@ubie-oss-data-engineering.iam.gserviceaccount.com"
