-- This was automatically generated by the `dbt-data-privacy` package.
{{
  config(
    materialized="view",
    database=var('data_analysis_layer'),
    schema="dbt_data_privacy_data_analysis_layer",
    alias="users",
    grant_access_to=[
      {
        "project": var('restricted_layer'),
        "dataset": "dbt_data_privacy_restricted_layer",
      },
    ],
    tags=['dbt_data_privacy', 'data_analysis'],
    labels={
      "modeled_by": "dbt",
    },
    persist_docs={'relation': True, 'columns': True},
    full_refresh=None,
    enabled=True
  )
}}

WITH privacy_protected_model AS (
  SELECT
    id AS `id`,
    SHA256(CAST(user_id AS STRING)) AS `user_id`,
  FROM
    {{ ref('restricted_layer__dbt_data_privacy_restricted_layer__users') }})

SELECT
  source.*,
FROM privacy_protected_model AS source
JOIN {{ ref("data_analysis_layer__dbt_data_privacy_data_analysis_layer__consents") }} AS target
  ON source.user_id = target.user_id
  WHERE
  consent.data_analysis IS TRUE
  
