name: Lint resources
on:
  pull_request:

jobs:
  check-style:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: lint-bash
        run: |
          sudo apt-get install -y shellcheck
          ./ci/lint_bash.sh

      - name: lint-yaml
        run: |
          sudo apt-get install -y yamllint
          ./ci/lint_yaml.sh
