name: Test the GitHub Actions
on:
  pull_request:
    paths:
      - .github/workflows/test-action.yml
      - action/**/*
      - integration_tests/models/**/schema.yml

jobs:
  notice-start-of-test:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Comment on PR start of test
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          body=$(cat <<EOF
          🚀 Starting the test action...
          Please check the workflow run for more details.
          URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          EOF
          )
          gh pr comment "${{ github.event.pull_request.number }}" \
            --body "${body}" \
            --repo "${{ github.repository }}"

  test-action:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      fail-fast: true
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
        dbt-version: ["1.8", "1.9", "1.10", "1.11"]
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ github.head_ref }}

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          cache-dependency-path: "integration_tests/pyproject.toml"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: projects/131500153501/locations/global/workloadIdentityPools/github-oidc-pool/providers/github-oidc-provider
          service_account: dbt-data-privacy@ubie-oss-data-engineering.iam.gserviceaccount.com

      - name: Test the action
        id: test-action
        working-directory: "integration_tests"
        env:
          PYTHON_VERSION: ${{ matrix.python-version }}
          DBT_VERSION: ${{ matrix.dbt-version }}
        run: |
          uv run nox -s "test_action-${PYTHON_VERSION}(dbt_version='${DBT_VERSION}')"

      - name: Delete .gitignore for the generated models
        shell: bash
        run: |
          rm -f "${{ github.workspace }}/integration_tests/models/.gitignore"
      - name: Push and revert the generated models
        shell: bash
        env:
          HEAD_REF: ${{ github.head_ref }}
        run: |
          # Confiture the git account
          git remote set-url origin "https://github-actions:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

          # Check if there are changes in models
          if [[ -n $(git status --porcelain "${{ github.workspace }}/integration_tests/models") ]]; then
            # Push the generated models
            git add "${{ github.workspace }}/integration_tests/models"
            git commit --signoff -m 'Generate dbt models by dbt-data-privacy'
            git push --set-upstream origin "HEAD:${HEAD_REF}"
            # Revert the commit
            git revert HEAD
            git push --force --set-upstream origin "HEAD:${HEAD_REF}"
          else
            echo "No changes in models to push."
          fi

  report-result:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    needs: test-action
    steps:
      - name: Comment on PR failure
        if: ${{ needs.test-action.result == 'failure' }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr comment "${{ github.event.pull_request.number }}" \
            --body "❌ One or more matrix jobs failed. Please check the workflow run for more details." \
            --repo "${{ github.repository }}" \
      - name: Comment on PR failure
        if: ${{ needs.test-action.result == 'success' }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr comment "${{ github.event.pull_request.number }}" \
            --body "✅ All matrix jobs passed. Please check the workflow run for more details." \
            --repo "${{ github.repository }}" \
