name: Unit tests with dbt Fusion
on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - .github/workflows/unit-tests-with-dbt-fusion.yml
      - macros/**/*
      - integration_tests/**/*

jobs:
  bigquery:
    # Add "id-token" with the intended permissions.
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup dbt Fusion
        run: |
          # The `dbt` command is installed as dbt Fusion in GitHub Action.
          curl -fsSL https://public.cdn.getdbt.com/fs/install/install.sh | sh -s -- --update
      # dbt-bigquery 1.9 required the application default credentials
      # SEE https://github.com/dbt-labs/dbt-bigquery/issues/1438
      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/131500153501/locations/global/workloadIdentityPools/github-oidc-pool/providers/github-oidc-provider
          service_account: dbt-data-privacy@ubie-oss-data-engineering.iam.gserviceaccount.com
      - name: Run unit tests
        id: run_unit_tests
        working-directory: "${{ github.workspace }}/integration_tests"
        run: |
          bash run_unit_tests.sh --target bigquery  --vars-path resources/vars/vars-bigquery.basic.yml
