name: Unit tests
on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - .github/workflows/unit-tests.yml
      - macros/**/*
      - integration_tests/**/*

jobs:
  bigquery:
    # Add "id-token" with the intended permissions.
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
        dbt-group: ["dbt-fusion", "dbt-core-1-10", "dbt-core-1-11"]
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # ratchet:actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # ratchet:astral-sh/setup-uv@v8.1.0
        with:
          enable-cache: true
          cache-dependency-glob: "integration_tests/pyproject.toml"
          python-version: ${{ matrix.python-version }}

      # dbt-bigquery 1.9 required the application default credentials
      # SEE https://github.com/dbt-labs/dbt-bigquery/issues/1438
      - uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093 # ratchet:google-github-actions/auth@v3
        with:
          workload_identity_provider: projects/131500153501/locations/global/workloadIdentityPools/github-oidc-pool/providers/github-oidc-provider
          service_account: dbt-data-privacy-gha@ubie-oss-data-engineering.iam.gserviceaccount.com

      - name: Run unit tests
        id: run_unit_tests
        working-directory: "integration_tests"
        run: |
          uv run nox -s "unit_tests-${{ matrix.python-version }}(uv_group='${{ matrix.dbt-group }}')"

      - name: Save logs and artifacts if failed
        if: always()
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # ratchet:actions/upload-artifact@v6
        with:
          name: save-logs-and-target-${{ matrix.python-version }}-${{ matrix.dbt-group }}
          retention-days: 3
          path: |
            integration_tests/logs
            integration_tests/target
      - id: exit
        if: steps.run_unit_tests.outcome != 'success'
        run: |
          exit 1
